[package]
name = "datafusion_util"
description = "Datafusion utilities"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
async-trait = "0.1"
datafusion = { workspace = true }
futures = "0.3"
object_store = { workspace = true }
pin-project = "1.1"
schema = { path = "../schema" }
tokio = { version = "1.47", features = ["parking_lot", "sync"] }
tokio-stream = "0.1"
tracing = { workspace = true }
url = "2.5"

