[package]
name = "trace"
description = "Distributed tracing support within IOx"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
chrono = { version = "0.4", default-features = false }
tracing = { workspace = true }
parking_lot = "0.12"
rand = "0.9"


[dev-dependencies]
