[package]
name = "backoff"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
tokio = { version = "1.47", features = ["macros", "time"] }
tracing = { workspace = true }
rand = "0.9"
snafu = "0.8"
