[package]
name = "predicate"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
arrow = { workspace = true }
async-trait = "0.1.89"
data_types = { path = "../data_types" }
datafusion = { workspace = true }
datafusion_util = { path = "../datafusion_util" }
futures = "0.3"
itertools = "0.13"
tracing = { workspace = true }
schema = { path = "../schema" }


[dev-dependencies]
query_functions = { path = "../query_functions"}
test_helpers = { path = "../test_helpers" }
