[package]
name = "client_util"
description = "Shared code for IOx clients"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
http = { workspace = true }
iox_http_util = { path = "../iox_http_util" }
reqwest = { workspace = true, features = ["stream", "rustls-tls-native-roots"] }
thiserror = "2.0.18"
tonic = { workspace = true, features = ["gzip", "tls-ring", "tls-native-roots", "zstd"] }
tower = { workspace = true }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
tokio = { version = "1.49", features = [
    "macros",
    "parking_lot",
    "rt-multi-thread",
] }
mockito = { version = "1.7", default-features = false }
